# Generated by Django 6.1 on 2026-08-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='face_profiles/')),
                ('embedding', models.BinaryField()),
                ('model_name', models.CharField(default='buffalo_l', max_length=50)),
                ('detection_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='VerificationAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cosine_similarity', models.FloatField(blank=True, null=True)),
                ('confidence_percent', models.FloatField(blank=True, null=True)),
                ('required_confidence_percent', models.FloatField(blank=True, null=True)),
                ('is_match', models.BooleanField(default=False)),
                ('error_code', models.CharField(blank=True, max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
