"""
Django settings for face_recognise project.

Generated by 'django-admin startproject' using Django 5.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q0n+civy$p=cw9!u(^exc1jcx5^w(8r!nie-x@2jgr=10g$b0o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'rest_framework.authtoken',

    'users',
    'services',
]

AUTH_USER_MODEL = 'users.User'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'face_verify': '20/min',
    },
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'face_recognise.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'face_recognise.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'


# Uploaded files (reference face images)

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Reject request bodies larger than 12 MB outright.
DATA_UPLOAD_MAX_MEMORY_SIZE = 12 * 1024 * 1024


# Face recognition
# ----------------
# InsightFace model pack. 'buffalo_l' is the accurate default (~330 MB,
# ArcFace w600k_r50, 512-d embeddings); 'buffalo_s' is smaller and faster.
FACE_MODEL_NAME = 'buffalo_l'

# Detector input size. Larger finds smaller faces at the cost of latency.
FACE_DET_SIZE = (640, 640)

# Discard detections the detector is not confident are faces at all.
FACE_MIN_DET_SCORE = 0.5

# A tightly-cropped headshot can defeat the detector, which expects some
# margin around the face. When the first pass finds nothing, the image is
# padded by this fraction of its shorter side and detection is retried.
FACE_DETECT_PAD_RATIO = 0.5

# Reject faces whose shorter bounding-box side is under this many pixels;
# tiny crops produce unreliable embeddings.
FACE_MIN_PIXELS = 50

# Refuse images containing more than one face, so a verification cannot be
# satisfied by a bystander. Set False to compare the largest face instead.
FACE_REJECT_MULTIPLE = True

# Cosine-similarity anchors used to calibrate the confidence percentage.
# ArcFace cosines are not percentages, so these map the raw score onto a
# 0-100 scale: FLOOR -> 0%, THRESHOLD -> 50%, CEILING -> 100%.
# Re-tune them for your own photos with: manage.py calibrate_face <dir>
FACE_COS_FLOOR = 0.10
FACE_COS_THRESHOLD = 0.40
FACE_COS_CEILING = 0.70

# Minimum calibrated confidence required to treat two faces as the same
# person. With the anchors above, 80% corresponds to a cosine of ~0.58.
FACE_MIN_CONFIDENCE = 80.0

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
